FROM prom/blackbox-exporter

# RUN addgroup --system --gid 1000 blackbox && \
#     adduser --system --uid 1000 --ingroup blackbox blackbox

# RUN chown -R blackbox:blackbox /bin/blackbox_exporter /etc/blackbox_exporter
# USER blackbox

EXPOSE 9115
