{
 "title": "New dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Duración total de las peticiones HTTP registradas en Prometheus",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "prometheus_http_request_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Número total de conexiones establecidas por el backend",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "net_conntrack_dialer_conn_established_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM utilizada por la aplicación",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tiempo total de CPU consumido",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 36 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Número de conexiones activas a la base de datos",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 49 },
   "targets": [
    { "expr": "pg_stat_database_numbackends", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tamaño base de datos",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "pg_database_size_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ratio de latencia peticiones HTTP incluido middleware",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_including_middlewares_seconds_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cantidad de solicitudes HTTP por vista y método",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 20, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "django_http_requests_total_by_view_transport_method_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cantidad de solicitudes HTTP por segundo por método",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Suma tiempo de latencia peticiones HTTP por vista y método",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 20, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum{instance=\"be:8000\"}[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}