{
 "title": "Transcendence",
 "description": "Monitoring transcendence app",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Django - Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(django_http_requests_body_total_bytes_count{instance=\"be:8000\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Postgres - Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Postgres Port",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_port{instance=\"postgres_exporter:9187\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bytes count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 5, "y": 10 },
   "targets": [
    {
     "expr": "django_http_requests_body_total_bytes_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "pg_database_connection_limit{datname=\"trascendence\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pg_settings_bonjour{server=\"db:5432\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}