# Generated by Django 5.1.5 on 2025-01-25 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("avatar", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Tournaments",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tournament_name", models.CharField(max_length=50)),
                ("start_date", models.DateTimeField(auto_now=True)),
                ("end_date", models.DateTimeField(auto_now=True)),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="tournaments_name", to="core.users"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stats",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("victories", models.IntegerField(default=0)),
                ("defeats", models.IntegerField(default=0)),
                ("total_matches", models.IntegerField(default=0)),
                ("total_tournaments", models.IntegerField(default=0)),
                ("tournaments_victories", models.IntegerField(default=0)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.users"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("result_user", models.IntegerField()),
                ("result_opponent", models.IntegerField()),
                ("type_match", models.CharField(max_length=50)),
                ("position_match", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("position_tournament", models.IntegerField()),
                (
                    "tournament_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tournaments",
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opponent",
                        to="core.users",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_history",
                        to="core.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Friends",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "declined"), (1, "accepted"), (2, "sent")]
                    ),
                ),
                (
                    "friend_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_friends",
                        to="core.users",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="core.users",
                    ),
                ),
            ],
        ),
    ]
