# Generated by Django 5.1.5 on 2025-02-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("entity_name", models.CharField(max_length=50)),
                ("record_id", models.IntegerField()),
                ("action", models.CharField(max_length=10)),
                ("old_data", models.JSONField(blank=True, null=True)),
                ("new_data", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("entity_id", models.IntegerField()),
            ],
        ),
    ]
