# Generated by Django 5.1.5 on 2025-01-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users_prueba',
            new_name='Users',
        ),
    ]
