# Generated by Django 5.1.5 on 2025-02-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friends",
            name="status",
            field=models.CharField(
                choices=[
                    ("declined", "Declined"),
                    ("accepted", "Accepted"),
                    ("sent", "Sent"),
                ],
                default="sent",
            ),
        ),
    ]
