# Generated by Django 5.1.5 on 2025-04-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_tournament_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tournament_display_name",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
